using InvoiceSystem.Configurations;
using InvoiceSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace InvoiceSystem.Data
{
    /// <summary>
    /// Application DbContext — EF Core Code First
    /// Features implemented:
    ///   ✔ Config Files       — via ApplyConfigurationsFromAssembly
    ///   ✔ Console Query Logger — via LogTo(Console.WriteLine)
    ///   ✔ Connection String  — read from appsettings.json
    /// </summary>
    public class AppDbContext : DbContext
    {
        // ── DbSets (one per Entity) ─────────────────────────────────
        public DbSet<Category>    Categories  { get; set; } = null!;
        public DbSet<Product>     Products    { get; set; } = null!;
        public DbSet<Customer>    Customers   { get; set; } = null!;
        public DbSet<Car>         Cars        { get; set; } = null!;
        public DbSet<Invoice>     Invoices    { get; set; } = null!;
        public DbSet<InvoiceItem> InvoiceItems { get; set; } = null!;

        // ── OnConfiguring ───────────────────────────────────────────
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                // ── Read Connection String from Config File ──────────
                IConfigurationRoot config = new ConfigurationBuilder()
                    .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                    .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                    .Build();

                string connectionString = config.GetConnectionString("DefaultConnection")
                    ?? throw new InvalidOperationException(
                        "Connection string 'DefaultConnection' not found in appsettings.json.");

                optionsBuilder
                    .UseSqlServer(connectionString)

                    // ── Console Query Logger ─────────────────────────
                    // Logs ALL SQL queries generated by EF Core to the console.
                    // FilteredByLevel ensures only Information+ logs are shown.
                    .LogTo(
                        message => Console.WriteLine(message),   // Output target
                        new[] { DbLoggerCategory.Database.Command.Name }, // Only SQL commands
                        LogLevel.Information,                    // Minimum log level
                        DbContextLoggerOptions.UtcTime           // Include UTC timestamp
                    )
                    .EnableSensitiveDataLogging()  // Shows parameter values in logs
                    .EnableDetailedErrors();       // More descriptive error messages
            }
        }

        // ── OnModelCreating ─────────────────────────────────────────
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // ── Apply All Config Files Automatically ─────────────────
            // Scans the assembly for all IEntityTypeConfiguration<T> classes
            // and applies them — no need to call each config manually.
            modelBuilder.ApplyConfigurationsFromAssembly(typeof(AppDbContext).Assembly);
        }
    }
}
